import { Header, Footer } from '@components'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: React.FC<NextPage> = () => {
	return (
		<div className="flex flex-col justify-between min-h-screen">
			<Head>
				<title>Epic Games Store</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />
			<h1 className="text-4xl font-bold">Hello Thømes</h1>
			<Footer />
		</div>
	)
}

export default Home
